version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-back
    ports:
      - "5000:80"
  front:
    build:
      context: .
      dockerfile: Dockerfile-front
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      BACKEND_HOST: web
      NODE_ENV: development
      NODE_PATH: /node_modules
    command: yarn start
