version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-back
    ports:
      - "5000:80"
  front:
    build:
      context: .
      dockerfile: Dockerfile-front
    ports:
      - "3000:3000"
    volumes:
      - ./:/opt/front
    environment:
      BACKEND_HOST: web
    command: yarn start
