FROM node:10-slim
ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV
ENV NDOE_PATH=/node_modules
EXPOSE 3000

COPY package.json yarn.lock /
RUN yarn && yarn cache clean
ENV PATH /node_modules/.bin:$PATH
WORKDIR /app

CMD [""]
