FROM node:10-slim
ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV
EXPOSE 3000

RUN mkdir /opt/front
WORKDIR /opt/front
COPY package.json package-lock.json* ./
RUN yarn && yarn cache clean
ENV PATH /opt/front/node_modules/.bin:$PATH

CMD ["yarn"]
